config/routes.rb
Rayons::Application.routes.draw do
  devise_for :users

  devise_scope :user do
    get "login", to: "devise/sessions#new"
    get "logout", to: "devise/sessions#destroy"
  end

  resources :items, except: [:new] do
    collection do
      post "import"
      post "import_discogs"
      get "random"
      get "latest"
      get "search"
      get "/page/:page", action: :index
    end
  end

  resources :stats, only: [:index] do
    collection do
      get "counts_by_day"
      get "time_machine"
      get "words_for_field"
    end
  end

  get "/stats/time_machine/:month/:day", to: "stats#time_machine"
  get "/mu-9306e982-5e21cfff-5e7a9bbe-e08bb3ce", to: "application#blitz"
  get "/opensearch.xml", to: "application#opensearch"
  get "/status", to: "application#status"
  root to: "items#index"
end

app/models/item.rb
class Item < ActiveRecord::Base
  before_validation :blank_discogs
  after_save :update_item_counts

  validates_presence_of :price_paid
  validates_format_of :discogs_url, with: URI.regexp(%w(http https)), allow_nil: true

  scope :added_on_day, ->(date) { where ["created_at >= ? AND created_at <= ?", date.to_date, (date + 1.day).to_date] }

  default_scope { where(deleted: false) }

  SORT_ORDER = %w(artist title year label format).freeze

  def self.search(query = "")
    query = query.to_s
    if !query.present?
      all
    elsif query == query.to_i.to_s
      ids = Item.basic_search(query).map(&:id)
      where(["year = ? OR id IN (?)", query, ids])
    else
      basic_search(query)
    end
  end

  def self.advanced_search(query = {})
    if !query.present?
      all
    else
      query = query.select { |_term, value| value.present? }
      if (years = query.delete("years"))
        if query.present?
          ids = Item.basic_search(query).map(&:id)
          where(["id IN (?) AND year BETWEEN ? AND ?", ids, years["minimum"], years["maximum"]])
        else
          where(["year BETWEEN ? AND ?", years["minimum"], years["maximum"]])
        end
      else
        basic_search(query)
      end
    end
  end

  def self.sorted(first = SORT_ORDER[0], direction = "ASC")
    first ||= SORT_ORDER[0]
    direction ||= "ASC"

    first = "to_number(price_paid, '9999999.99')" if first == "price_paid"
    sort_order = [first] + (SORT_ORDER - [first])
    sort_order = sort_order.map { |s| "#{s} #{direction}" }

    order(sort_order.join(","))
  end

  # Generate CSV of items and yield each row to a block
  def self.to_csv
    headers = Item.column_names - %w(id deleted)
    csv = ""

    csv << CSV::Row.new(headers, headers, true).to_s
    yield csv if block_given?

    Item.find_each(batch_size: 50) do |item|
      values = item.attributes.values_at(*headers)
      row = CSV::Row.new(headers, values, false).to_s
      yield row if block_given?
      csv << row
    end
    csv
  end

  # Import a csv file object and create an Item object for each row
  #
  # @param [File] file The csv file to be read
  # @return [Array] The array of items created
  def self.import_csv_file(file)
    raise "You must include a file" unless file

    # construct an array of hashes from the data
    # from http://snippets.dzone.com/posts/show/3899
    csv_data = CSV.read(file.tempfile)
    headers = csv_data.shift.map(&:to_s)
    string_data = csv_data.map { |row| row.map { |cell| cell.to_s.force_encoding("utf-8") } }
    array_of_hashes = string_data.map { |row| Hash[*headers.zip(row).flatten] }

    items = []

    Item.transaction do
      array_of_hashes.each { |attrs| items << Item.create(attrs) }
    end

    items
  end

  def added_on
    created_at.strftime("%m.%d.%y")
  end

  def as_json(options = {})
    super(options.merge(methods: :added_on))
  end

  def destroy
    self.deleted = true
    save!
  end

  private

  def blank_discogs
    self.discogs_url = nil if discogs_url.blank?
  end

  def update_item_counts
    ItemCount.update_or_create_day created_at.to_date
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  include ApplicationHelper
  include ActionController::Live

  before_action :authorize_item, only: [:new, :edit, :create, :update, :import, :destroy, :show]
  before_action :edit_discogs_param, only: [:index, :create, :update]
  before_action :set_variant, only: [:show]

  # GET /
  # GET /items
  # GET /items.json
  # GET /items.csv
  def index
    respond_to do |format|
      format.html { @can_edit = policy(Item).edit? }
      format.json { index_json }
      format.csv { index_csv }
    end
  end

  # GET /items/latest.json
  def latest
    number_of_items = params[:num].to_i
    number_of_items = 5 if number_of_items.zero?
    @items = Item.order("created_at DESC").limit(number_of_items)
    render json: @items
  end

  # GET /items/1
  # GET /items/1.json
  def show
    @item = Item.find(params[:id])

    respond_to do |format|
      format.html do
        render html: (cache [@item, request.variant, "1"] do
          @release = DiscogsRelease.new(@item)
          render_to_string
        end)
      end
      format.json { render json: @item }
    end
  end

  # GET /items/1/edit
  def edit
    @item = Item.find(params[:id])
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: "Item was successfully created." }
        format.json { render json: @item, status: :created, location: @item }
      else
        default_error_response(format, "new", @item)
      end
    end
  end

  # PUT /items/1
  # PUT /items/1.json
  def update
    @item = Item.find(params[:id])
    params[:item] = params[:item].reject { |k, _| !Item.column_names.include?(k) }

    respond_to do |format|
      if @item.update_attributes(item_params)
        format.html { redirect_to @item, notice: "Item was successfully updated." }
        format.json { head :no_content }
      else
        default_error_response(format, "edit", @item)
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item = Item.find(params[:id])
    @item.destroy

    respond_to do |format|
      format.html { redirect_to items_url }
      format.json { head :no_content }
    end
  end

  # POST /items/import
  def import
    @items = Item.import_csv_file(params[:file])
    flash[:notice] = "Imported #{@items.count} items"

  rescue => e
    flash[:error] = "Error importing: #{e}"
    Rails.logger.warn("!!! Error importing CSV: #{e}")
    Rails.logger.warn(e.backtrace.join("\n"))
  ensure
    redirect_to "/"
  end

  # POST /items/import_discogs
  def import_discogs
    @item = DiscogsImporter.new(params[:url]).import
    redirect_to edit_item_path(@item)
  rescue => e
    flash[:error] = "Error importing: #{e}"
    Rails.logger.warn("!!! Error importing CSV: #{e}")
    Rails.logger.warn(e.backtrace.join("\n"))
    redirect_to "/"
  end

  # GET /items/random
  # GET /items/random.json
  def random
    @item = Item.offset(rand(Item.count)).first

    respond_to do |format|
      format.html { redirect_to @item }
      format.json { render json: @item }
    end
  end

  def search
    @presenter = ItemSearchPresenter.new
  end

  private

  def authorize_item
    authorize Item
  end

  def edit_discogs_param
    params[:sort] = "discogs_url" if params[:sort] == "discogs"
    if params[:item]
      params[:item][:discogs_url] ||= params[:item][:discogs]
    end
  end

  def item_params
    params.require(:item).permit(:artist, :condition, :format, :label, :price_paid, :title, :year, :color, :notes, :discogs_url)
  end

  def set_variant
    request.variant = :editable if policy(:item).update?
  end

  def index_json
    if params[:q]
      params[:q] = params[:q].permit(:title, :artist, :format, :label, :color, :condition, :notes, years: [:minimum, :maximum])
      presenter = ItemAdvancedSearchJSONPresenter.new(params.slice(:sort, :direction, :q, :page))
    else
      presenter = ItemJSONPresenter.new(params.slice(:sort, :direction, :search, :page))
    end

    body = Rails.cache.fetch presenter.cache_key do
      markup = render_to_string(partial: "items/pagination", formats: [:html], locals: { items: presenter.items }).gsub(/.json/, "")
      presenter.as_json.merge(pagination: markup).to_json
    end

    render json: body
  end

  def index_csv
    set_streaming_headers
    headers.merge!("Content-Type" => "text/csv",
                   "Content-disposition" => "attachment; filename=\"rayons_#{Time.now.to_i}.csv\"")
    Item.to_csv { |row| response.stream.write row }
    response.stream.close
  end
end

app/helpers/items_helper.rb
module ItemsHelper
  def discogs_percent
    number_with_url = Item.where("discogs_url IS NOT NULL").count
    "#{number_with_delimiter(number_with_url)} / #{number_with_delimiter(Item.count)}"
  end

  def google_column_charts_options
    {
      backgroundColor: "white",
      colors: ["#FBBE1E"],
    }
  end

  def google_pie_charts_options
    {
      backgroundColor: {
        fill: "white",
        stroke: "white",
      },
      colors: ["#1A739F", "#FBBE1E", "#FB4C1E", "#094A6A", "#2C6079", "#BF9B3F", "#BF5A3F", "#094A6A", "#A77B0A", "#A72B0A", "#49A1CC", "#FDCE53", "#FD7653", "#6AACCC", "#FDD97D", "#FD977D"].shuffle,
      pieSliceBorderColor: "#222",
      pieSliceText: "label",
      pieSliceTextStyle: { color: "black", fontSize: "12" },
      legend: { position: "none" },
    }
  end

  def items_per_month
    Item.group_by_month(:created_at, format: "%b %Y").count
  end

  def items_per_day_of_week
    days_of_week = %w(Sunday Monday Tuesday Wednesday Thursday Friday Saturday)
    result = {}
    Item.group_by_day_of_week(:created_at).count.map do |k, v|
      result[days_of_week[k.to_i]] = v
    end
    result
  end

  def random_discogsless_url
    item_url(Item.where("discogs_url IS NULL").sample)
  end

  def top_10(field)
    @total_count ||= Item.count
    stats = @item_stats || ItemStats.new
    stats.stats_for_field(field).first(10).map do |value, count|
      percentage = count * 100.0 / @total_count
      "<p><strong>#{value}</strong>: #{number_with_delimiter(count)}: <em>#{percentage.round(2)}%</em></p>"
    end.join.html_safe
  end

  def field_headers
    ["Title", "Artist", "Year", "Label", "Format", "Condition", "Color", "Price Paid", "Discogs", "Notes"]
  end
end

app/views/items/_form.html.haml
= form_for @item do |f|
  - if @item.errors.any?
    #error_explanation
      %h2= "#{pluralize(@item.errors.count, "error")} prohibited this item from being saved:"
      %ul
        - @item.errors.full_messages.each do |msg|
          %li= msg

  - (Item.column_names - ['id', 'created_at', 'updated_at', 'deleted']).each do |field|
    .form-group
      = f.label field
      = f.text_field field, class: "form-control"
  .form-group
    %button.btn.btn-primary{ type: "submit" } Save

app/views/items/_pagination.html.haml
= paginate(items)

app/views/items/_template.html.erb
<tr data-id='{{id}}'>
  <td class='item-title'>{{title}}</td>
  <td class='item-artist'>{{artist}}</td>
  <td class='item-year'>{{year}}</td>
  <td class='item-label'>{{label}}</td>
  <td class='item-format'>{{format}}</td>
  <td class='item-condition'>{{condition}}</td>
  <td class='item-color'>{{color}}</td>
  <td class='item-price_paid'>{{price_paid}}</td>
  <td class='item-discogs_url'>
    {{#discogs_url}}
      <a href='{{discogs_url}}' target='_blank'>link</a>
    {{/discogs_url}}
  </td>
  <td class='item-notes'>{{notes}}</td>
  <td class='item-added_on'>{{added_on}}</td>
  <td class='item-edit'>
    <a href='/items/{{id}}'>s</a><% if policy(Item).edit? %>/<a class='item-edit' href='/items/{{id}}/edit'>e</a>/<a class='item-delete' href='/items/{{id}}'>d</a><% end %>
  </td>
</tr>

app/views/items/edit.html.haml
.container-fluid
  %h1 Edit

  = render 'form'

  .row
    .col-md-12
      = link_to 'Show', @item
      \|
      = link_to 'Back', :back

app/views/items/index.html.haml
.container-fluid#items
  #add-new.text-center
    - if @can_edit
      %form.form-inline.ajax{ :action => '/items', :method => 'post' }
        .form-group
          = token_tag(nil)
          - field_headers.each do |field|
            %input.form-control{ :type => 'text', :name => "item[#{field.parameterize(separator: "_")}]", :placeholder => field }
          %button.btn.btn-primary{ :type => 'submit' } Add

  .table-responsive
    %table.table{ 'data-sort' => params[:sort], 'data-direction' => params[:direction] }
      %thead
        %tr
          - field_headers.each do |field|
            %th{ :class => "item-#{field.parameterize(separator: "_")}" }
              - sort = field.parameterize(separator: "_")
              %a{ :href => '', 'data-sort' => sort }
                - if field == "Price Paid"
                  Paid
                - else
                  = field
          %th
            %a.added_on{ :href => '', 'data-sort' => 'created_at'}
              Added
          %th
      %tbody.js-items
  .js-pagination
  .loader.js-loader
    - 12.times do
      %li

%script#item_template{ type: 'text/template' }= render :partial => '/items/template'

:javascript
  window.filter_options = #{params.slice(:sort, :direction, :search, :q, :page).to_json};

- content_for :nav do
  %ul.nav.navbar-nav
    %li
      %a.js-items-page-info
    %li
      %a{ :href => '/stats' } stats
    %li
      %a{ :href => random_items_path } random
    - if @can_edit
      %li
        %a.logout{ :href => '/logout' } log out
      %li
        %a.import{ :href => '' } import
        %form.navbar-form.login.collapse{ :action => '/items/import_discogs', :method => 'post'}
          .form-group
            = token_tag(nil)
            %input.form-control{ :type => 'text', :name => 'url', :placeholder => "Discogs URL" }
            %input.form-control{ :type => 'submit', :value => 'Import' }
      %li
        %a.import{ :href => '' } import csv
        %form.navbar-form.login.collapse{ :action => '/items/import', :method => 'post', :enctype => 'multipart/form-data'}
          .form-group
            = token_tag(nil)
            %input.form-control{ :type => 'file', :name => 'file' }
            %input.form-control{ :type => 'submit', :value => 'Import' }
    - else
      %li
        %a.login{ :href => '' } log in
        = form_tag user_session_path, class: "navbar-form collapse" do
          .form-group
            = text_field_tag 'user[email]', nil, :placeholder => 'Email Address', class: "form-control"
            = password_field_tag 'user[password]', nil, :placeholder => 'Password', class: "form-control"
          %button.btn.btn-default{ type: "submit" } Sign in
    %li
      %form.search.navbar-form.js-search{ :action => '/', :method => 'get' }
        .form-group
          %input.search-input.form-control{ :type => 'search', :name => 'search', :placeholder => 'Search', :value => params[:search] }
    %li
      %a{ href: search_items_path } advanced

app/views/items/new.html.haml
%h1 New item

= render 'form'

= link_to 'Back', items_path

app/views/items/search.html.haml
.container-fluid#item_search
  %h1 Advanced Search

  = form_for(:q, url: "/", method: "GET") do |f|
    .form-group
      - %w[title artist label color notes].each do |field|
        .form-group
          = f.label field, "#{field.titleize}:"
          = f.text_field field, class: "form-control"

      .form-group
        = f.label :year, "Year:"
        %br
        = f.fields_for :years do |years|
          = years.number_field :minimum, value: @presenter.minimum_year
          to
          = years.number_field :maximum, value: @presenter.maximum_year

      - %w[format condition].each do |field|
        .form-group
          = f.label field, "#{field.titleize}:"
          = f.select field, [], {}, class: "form-control" do
            = options_for_select [""] + @presenter.send(field.pluralize)

      .form-group
        %button.btn.btn-primary.btn-large{ type: "submit" } Search

app/views/items/show.html+editable.haml
- content_for :title, "#{@item.artist} - #{@item.title}"

.container-fluid#item_show
  %h1
    #{@item.artist} -
    %em= @item.title
  %h2
    #{@item.format} released in #{@item.year} on #{@item.label}
  %h3
    Added on #{@item.created_at.strftime('%A, %B %-d, %Y')}

  .row
    - if @release.image_url.present?
      .col-md-4.image
        %img.img-responsive{ src: @release.image_url }
        %br
    .col-md-8
      %p
        %b Condition:
        = @item.condition
      %p
        %b Color:
        = @item.color
      %p
        %b Price paid:
        = @item.price_paid
      - if @release.extra_info?
        %p
          %b Genre:
          = @release.genres.to_a.join(', ')
        %p
          %b Style:
          = @release.styles.to_a.join(', ')
        - if @release.tracklist
          .tracklist
            %b Tracklist
            %ul
              - @release.tracklist.each do |track|
                %li #{track.position}: #{track.title}
      - if @release.notes.present?
        %p
          %b Notes:
          %br
          - @release.notes.to_s.lines.each do |line|
            = line.html_safe
            %br
        %p
          %a{ href: @item.discogs_url, target: '_blank' } Discogs Link
      %p
        %a{ href: edit_item_path(@item) } Edit

- content_for :nav do
  %ul.nav.navbar-nav
    %li
      %a{ :href => '/stats' } stats
    %li
      %a{ :href => random_items_path } random
    %li
      %a.logout{ :href => '/logout' } log out
    %li
      %form.search.navbar-form.js-search{ :action => '/', :method => 'get' }
        .form-group
          %input.search-input.form-control{ :type => 'search', :name => 'search', :placeholder => 'Search', :value => params[:search] }

app/views/items/show.html.haml
- content_for :title, "#{@item.artist} - #{@item.title}"

.container-fluid#item_show
  %h1
    #{@item.artist} -
    %em= @item.title
  %h2
    #{@item.format} released in #{@item.year} on #{@item.label}
  %h3
    Added on #{@item.created_at.strftime('%A, %B %-d, %Y')}

  .row
    - if @release.image_url.present?
      .col-md-4.image
        %img.img-responsive{ src: @release.image_url }
        %br
    .col-md-8
      %p
        %b Condition:
        = @item.condition
      %p
        %b Color:
        = @item.color
      %p
        %b Price paid:
        = @item.price_paid
      - if @release.extra_info?
        %p
          %b Genre:
          = @release.genres.to_a.join(', ')
        %p
          %b Style:
          = @release.styles.to_a.join(', ')
        - if @release.tracklist
          .tracklist
            %b Tracklist
            %ul
              - @release.tracklist.each do |track|
                %li #{track.position}: #{track.title}
      - if @release.notes.present?
        %p
          %b Notes:
          %br
          - @release.notes.to_s.lines.each do |line|
            = line.html_safe
            %br
        %p
          %a{ href: @item.discogs_url, target: '_blank' } Discogs Link

- content_for :nav do
  %ul.nav.navbar-nav
    %li
      %a{ :href => '/stats' } stats
    %li
      %a{ :href => random_items_path } random
    %li
      %a.logout{ :href => '/logout' } log out
    %li
      %form.search.navbar-form.js-search{ :action => '/', :method => 'get' }
        .form-group
          %input.search-input.form-control{ :type => 'search', :name => 'search', :placeholder => 'Search', :value => params[:search] }